dvd/urls.py
from django.urls import path
from dvd import views

app_name = 'dvd'

urlpatterns = [
    path('add/<int:movie_id>', views.add_movie_cart, name='add_movie'),
    path('remove/<int:movie_id>', views.remove_movie_cart, name='remove_movie'),
    path('', views.cart_detail, name='cart_detail'),
    ]

login/urls.py
from django.urls import path
from login import views
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns =[
    path('', views.LogginIn, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.CreateUser, name='register'),
    ]

movie/urls.py
from django.urls import path
from movie import views

app_name = 'movie'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('search/', views.search, name = 'search'),
    path('detail/<int:search_id>/', views.detail, name = 'detail'),
    #path('add/<str:search_id>/<str:search_overview>/<str:search_release_date>/', views.add, name = 'add'),
    path('add/<int:search_id>', views.add, name = 'add'),
    path('user_list/', views.user_list, name='user_list'),
    path('delete/<int:movie_id>/', views.delete_movie, name = 'delete_movie')
    ] 
    
    

moviewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dvd/', include('dvd.urls', namespace='dvd')),
    path('login/', include('login.urls', namespace='login')),
    path('', include('movie.urls', namespace = 'movie')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movie/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class movie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    title = models.CharField(max_length=255)
    description = models.TextField()
    year = models.DateField()
    rating = models.FloatField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=10.00)
    
    def __str__(self):
        return self.title

movie/forms.py
from django import forms

movie/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
import requests
from django.views.decorators.http import require_POST, require_GET
from django.http import HttpResponseRedirect
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib import messages
from django.utils.dateparse import parse_date
from dvd.forms import dvd_forms
from django.contrib.auth.decorators import login_required

from .models import movie
# Create your views here.

base_url = 'https://api.themoviedb.org/3/'
api_key = '44546d0b46d2674ccb7766f74d0369f0'

def home(request):
    return render(request, 'movie/home.html')

@login_required    
def dashboard(request):
    user = request.user
    movie_list = movie.objects.filter(user=user)
    length_list = len(movie_list)
    return render(request, 'movie/dashboard.html', {'length_list': length_list})

def search(request):
    search_query = request.GET.get('q')
    url = f'{base_url}search/movie?api_key={api_key}&query={search_query}'
    search = requests.get(url)
    search = search.json()
    results = {'searches': search}
    
    return render(request, 'movie/search.html', context = results)
    
def detail(request, search_id):
    url = f'{base_url}movie/{search_id}?api_key={api_key}'
    search_detail = requests.get(url)
    search_detail = search_detail.json()
    search_result = {'search_detail': search_detail}
    
    return render(request, 'movie/detail.html', context=search_result)
    


def add(request, search_id):
    if request.method == 'POST':
        url = f'{base_url}movie/{search_id}?api_key={api_key}'
        search_detail = requests.get(url)
        search_detail = search_detail.json()
        temp_date = parse_date(search_detail['release_date'])
        if request.user.is_authenticated:
            if movie.objects.filter(title=search_detail['title'], user=request.user).exists():
                return HttpResponse('It is already saved in the list')
            else:    
                save_item = movie(title=search_detail['title'], description=search_detail['overview'], year=temp_date)
                save_item.user = request.user
                save_item.save()
                messages.success(request, 'saved')
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            return HttpResponse('<h1> user is not authenticated </h1>')
            
    elif request.method == 'GET':
        pass
    
    return render(request, 'movie/add.html')


def user_list(request):
    movie_list = movie.objects.filter(user=request.user)
    form = dvd_forms()
    return render(request, 'movie/user_list.html', {'movie_list': movie_list, 'form': form})
    
def delete_movie(request, movie_id):
    if request.method == 'GET':
        get_movie = get_object_or_404(movie, id = movie_id)
        get_movie.delete()
        messages.success(request, 'movie deleted')
        
    return redirect('movie:user_list')
        
        
        
        
        
"""
@require_POST  
def add(request, search_id, search_overview, search_date):
    if request.method == 'POST':
        form = request.method['POST']
        add_movie = movie(title=form['search_id'], description=form['search_overview'], year=form['search_date'])
        add_movie.save()
    return HttpResponseRedirect(request.path_info)

@require_POST  
def add(request, search_id, search_overview):
    if request.method == 'POST':
        add_movie = movie(title=search_id, description=search_overview)
        add_movie.save()
    return redirect('home')
    
@require_GET
def add(request, search_id, search_overview):
    pass
    



def add(request, search_id):
    if request.method == 'POST':
        url = f'{base_url}movie/{search_id}?api_key={api_key}'
        search_detail = requests.get(url)
        search_detail = search_detail.json()
        if request.user.is_authenticated:
            if search_detail['title']:
                save_item = movie(title=search_detail['title'])
                save_item.user = request.user
                save_item.save()
                
                
        else:
            return HttpResponse('<h1> user is not authenticated </h1>')
            
    elif request.method == 'GET':
        pass
    return render(request, 'movie/add.html')
    
"""    

movie/templates/movie/add.html
{% extends 'movie/base.html' %}

{% block title %} Yeah something {% endblock %}

{% block content %}

<h1> Test </h1>

{% endblock %}

movie/templates/movie/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
        <title> 
        
        {% block title %} {% endblock %}
        
        </title>
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </head>
    
<body class='container'>
    {% if user.is_authenticated %}
    <header class='header'>
    <nav class = 'nav-bar' >
        <a href="{% url 'movie:user_list' %}">Movie List</a>
        
        <a href="{% url 'dvd:cart_detail' %}">
            Cart
            {% with item=cart|length %}
            {% if cart|length > 0 %}
            ({{ item }} item{{item|pluralize}})
            {% else %}
            ( 0 item )
            {% endif %}
            {% endwith %}
            </a>
        <a href="{% url 'login:logout' %}">Logout</a>  
    </nav>
    </header>
  
    
    {% else %}
    
    <header class='header'>
    <nav class = 'nav-bar' >
        <a href="{% url 'login:login' %}">Login</a>
        
        <a href="/">Register</a>
    </nav>
    </header>
     
    {% endif %}
    {% block content %} {% endblock %}
</body>    
</html>

movie/templates/movie/dashboard.html
{% extends 'movie/base.html' %}

{% block title %} Dash Board {% endblock %}

{% block content %} 

<h1>Welcome Home</h1>

{% if length_list > 0 %}
<h2>
    Begin by searching for a movie or edit your <a href="{% url 'movie:user_list' %}"> movie list </a>
</h2>

<form action='search/' method='get'>
    <input type="text" name="q"/>
    <input type="submit" value="Search"/>
</form>

{% else %}

<h2> Begin by Searching for a movie </h2>

<form action='search/' method='get'>
    <input type="text" name="q"/>
    <input type="submit" value="Submit"/>
</form>

{% endif %}




{% endblock %}

movie/templates/movie/detail.html
}{% extends 'movie/base.html' %}

{% block title %} Detail {% endblock %}

{% block content %}



<h3> {{search_detail.title}} </h3>
<h3> {{search_detail.belongs_to_collection}}</h3>

{% endblock %}

movie/templates/movie/home.html
{% extends 'movie/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

{% else %}
<div class='full-height-grow main-text'>
<h1 class='main-texts'> Create your own movie list and buy them </h1>
<a href="{% url 'login:login' %}" class='btn'> Join now </a>
</div>
{% endif %}

{% endblock %}

movie/templates/movie/search.html
{% extends 'movie/base.html' %}

{% block title %} Your Search Results {% endblock %}

{% block content %}
<h1>
    Your Search results
</h1>

<h2>
{% for search in searches.results%}
<p>
<a href= "{% url 'movie:detail' search.id %}">{{search.title}} </a>
<h2> {{search.release_date}} </h2>
<form action = "{% url 'movie:add' search.id %}" method = 'post'>
    {% csrf_token %}
    <input type="submit" value="add"/>
</form>
</p>
{% endfor %}
</h2>

<h3>
    {{test}}
    
</h3>

{% endblock %}

movie/templates/movie/user_list.html
{% extends 'movie/base.html' %}

{% block title %} 
Your list 
{% endblock %}

{% block content %} 

{% for movie in movie_list %}
<h1> {{ movie.title }} </h1>
<h2> {{ movie.description|truncatewords:30 }}</h2>
<h3> Released in {{ movie.year }}</h3>
<form action = "{% url 'movie:delete_movie' movie.id %}" method='get'>
    <input type="submit" value="Delete"/>
</form>
<form action="{% url 'dvd:add_movie' movie.id %}" method='post'>
    {% csrf_token %}
    {{form}}
    <input type='submit' value='add to cart'>
</form>
{% empty %}
<h1> No Movies has been added yet </h1> 
{% endfor %}
{% endblock %}